name: Sync and rebrand

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * FRI"

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          upstream_repo: https://github.com/gobitfly/eth2-beaconchain-explorer.git
          upstream_branch: master
          downstream_branch: master
          token: ${{ secrets.GH_TOKEN }}

      # - name: Create release branch
      #   run: git checkout -b release/lukso-automation

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Replace ETH currencies
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '\bETH\b'
          replace: "LYXE"
          regex: true
          exclude: ".git**"

      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add -A
          git commit -m "[Automated Commit] Change ETH to LYX"

      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v
          
      # - name: Bump version and push tag
      #   uses: anothrNick/github-tag-action@1.36.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #     WITH_V: true

      # - name: Push new branch
      #   run: git push origin release/lukso-automation

      # - name: Create pull request into master
      #   uses: thomaseizinger/create-pull-request@1.0.0
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #     head: release/lukso-automation
      #     base: master
      #     title: "[Automated PR] Find and replace currency"
      #     body: |
      #       This PR was created in response of workflow running on weekly basis or manual trigger.
      #       This is a forked repo of https://github.com/gobitfly/eth2-beaconchain-explorer which is activly maintained.
      #       The workflow checks on a weekly basis for new updates and merges it into our repo, afterwards this Automated PR is created to rebrand the application.