name: Build Lukso Explorer Consensus

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  IMAGE_NAME: europe-docker.pkg.dev/lks-lz-artifacts/docker-beacon-explorer/beacon-explorer

jobs:
  explorer-consensus:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@v0
        with:
          service_account_key: "artifact-deployer@lks-lz-management.iam.gserviceaccount.com"
          project_id: "projects/311968610280/locations/global/workloadIdentityPools/github/providers/github"
          export_default_credentials: true

      - name: Image
        run: |-
          docker build -t europe-docker.pkg.dev/lks-lz-artifacts/docker-beacon-explorer/beacon-explorer:${{ github.ref_name }} .

      - run: |
          gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Build
        run: |-
          docker push europe-docker.pkg.dev/lks-lz-artifacts/docker-beacon-explorer/beacon-explorer:${{ github.ref_name }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: "Set up Cloud SDK"
      #   uses: "google-github-actions/setup-gcloud@v0"

      # - id: gcpauth
      #   name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v0
      #   with:
      #     create_credentials_file: "true"
      #     workload_identity_provider: "projects/311968610280/locations/global/workloadIdentityPools/github/providers/github"
      #     service_account: "artifact-deployer@lks-lz-management.iam.gserviceaccount.com"

      # - name: login
      #   run: |-
      #     gcloud auth login --brief --cred-file="${{ steps.gcpauth.outputs.credentials_file_path }}"
      #     gcloud auth configure-docker europe-docker.pkg.dev
      
      # - name: Geth Client GO
      #   uses: docker/build-push-action@v3
      #   with:
      #     file: ./Dockerfile
      #     platforms: linux/amd64
      #     push: true
      #     tags: |
      #       ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
      #       ${{ env.IMAGE_NAME }}:latest
      #     github-token: ${{ secrets.GH_TOKEN }}
